export default function Transparency() {
  return (
  <div class="paragraph-container">
    <p class="paragraph">
    It is important to note that, by no means am I a professional in the fields of journalism, data science, or impartiality. The sentiment analysis tool that I have developed is a general-purpose tool and should not be used as a sole source of information.
    </p>
    <p class="paragraph">
    The happiness index generated by this tool is calculated using a formula that acts as a weighted average of the sentiment analysis of headlines that have been scraped and subsequently translated using the AWS service.
    You can find the list of sources at the following link: <a href="https://github.com/TerenceGrover/HSTW/blob/main/server/data/sourceLinks.json">Source Links</a>.
    The color on the globe on the front page is then calculated using a separate formula to enhance the visual impact of the index.
    </p>
    <div class="formula-transparency">
      Index Formula 
    </div>
    <div class="formula-transparency">
      Color Formula 
    </div>
    <p class="paragraph">
    It is important to note that the sentiment analysis performed is based on the headlines of news articles and may not accurately reflect the sentiment of the entire article. Additionally, the translation service used may introduce inaccuracies in the sentiment analysis.
    </p>
    <p class="paragraph">
    As the developer of this tool, I am committed to transparency and open communication with users. If you have any recommendations or suggestions for improvements, I would gladly implement any changes that are suggested.
    </p>
  </div>

  );
}
